<div class='intro'>
  <h1>Welcome to Elmo</h1>

  <p>
    St. Elmo's fire (also St. Elmo's light) is a weather phenomenon in which luminous plasma is created by a coronal discharge from a sharp or pointed object in a strong electric field in the atmosphere (such as those generated by thunderstorms or created by a volcanic eruption). <a href="http://en.wikipedia.org/wiki/St._Elmo's_fire">Wikipedia</a>
  </p>
</div>